version: '3'

services:
  launcher-client:
    build:
      context: ./launcher/client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - './envs/.production/.launcher-client'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`xyz.com`)"
      - "traefik.http.routers.frontend.entrypoints=https"
      - "traefik.http.routers.frontend.tls=true"
    networks:
      - traefik_network

  backend:
    build:
      context: ./launcher-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.xyz.com`)"
      - "traefik.http.routers.backend.entrypoints=https"
      - "traefik.http.routers.backend.tls=true"
    networks:
      - traefik_network

  traefik:
    image: traefik:v2.4
    restart: always
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=your_email@xyz.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=false"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik_network

networks:
  traefik_network:
    external:
      name: traefik_network
