name: Update Containers

on:
  workflow_run:
    workflows:
      - Build Docker containers
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd linked-trust-content-mod 
            git pull origin main 
            docker compose -f dev.yaml --env-file .env.development pull
            docker compose -f dev.yaml --env-file .env.development up -d
