name: Build Docker containers

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_TAG: latest
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_NAME1: launcher-client
  DOCKER_IMAGE_NAME2: launcher-server
  DOCKER_IMAGE_NAME3: exchange-client
  DOCKER_IMAGE_NAME4: launcher-service
  DOCKER_IMAGE_NAME5: recording-oracle
  DOCKER_IMAGE_NAME6: reputation-oracle

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker image launcher client
        run: docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME1:$DOCKER_IMAGE_TAG -f ./launcher/client/Dockerfile .

      - name: Push Docker image launcher client to Docker Hub
        run: docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME1:$DOCKER_IMAGE_TAG

      - name: Build Docker image launcher server
        run: docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME2:$DOCKER_IMAGE_TAG -f ./launcher/server/Dockerfile .

      - name: Push Docker image launcher server to Docker Hub
        run: docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME2:$DOCKER_IMAGE_TAG

      - name: Build Docker image exchange UI
        run: docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME3:$DOCKER_IMAGE_TAG -f ./exchange/Dockerfile .

      - name: Push Docker image exchange UI to Docker Hub
        run: docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME3:$DOCKER_IMAGE_TAG

      - name: Build Docker image launcher service
        run: docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME4:$DOCKER_IMAGE_TAG -f ./launcher-service/Dockerfile .

      - name: Push Docker image launcher service to Docker Hub
        run: docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME4:$DOCKER_IMAGE_TAG

      - name: Build Docker image recording oracle
        run: docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME5:$DOCKER_IMAGE_TAG -f ./recording-oracle/Dockerfile .

      - name: Push Docker image recording oracle to Docker Hub
        run: docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME5:$DOCKER_IMAGE_TAG

      - name: Build Docker image reputation oracle
        run: docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME6:$DOCKER_IMAGE_TAG -f ./reputation-oracle/Dockerfile .

      - name: Push Docker image reputation oracle to Docker Hub
        run: docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME6:$DOCKER_IMAGE_TAG
